name: sim_card_info
description: "A Flutter plugin for accessing SIM card and getting Phone number Country Code."
version: 0.0.4

repository: https://github.com/mustafa-707/sim_card_info
issue_tracker: https://github.com/mustafa-707/sim_card_info/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.sim_card_info
        pluginClass: SimCardInfoPlugin
      ios:
        pluginClass: SimCardInfoPlugin
