name: sim_card_code
description: "A Flutter plugin for accessing SIM card and getting Phone number Country Code."
version: 0.0.2

repository: https://github.com/mustafa-707/sim_card_info
issue_tracker: https://github.com/mustafa-707/sim_card_info/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.sim_card_code
        pluginClass: SimCardCodePlugin
      ios:
        pluginClass: SimCardCodePlugin
